name: Label Customer Issues

on:
  issues:
    types: [opened]
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  label_customer_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: dolthub/label-customer-issues@0533b85a589e4f078277eed4b55523ebfbd2c7c6
        with:
          repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          issue-label: customer issue
          pr-label: contribution
          exclude: dependabot